### ISSUE TITLE
syntax validation error - toLower()

### ISSUE THREAD

**Issue by iamGavinJ** [GillesZunino/Sublime-AzureResourceManager#1]
Hi @GillesZunino, not sure if you're still maintaining this but there's an issue with the syntax checking for the toLower() function.

When pulling a parameter from an object type, the syntax validator fails to 'see' the trailing bracket and therefore the remaining entirety of the document doesn't highlight properly.

e.g.
"variables": {
  "vmName": "[concat(  toLower(parameters('env').vmName),'-vm')]"
}

**Comment by GillesZunino** [comment]
Thank you for reporting this. Will take a look at it.
